---

 - hosts: clients
   tasks:
 
   - name: install updates (CentOS)
     tags: always
     dnf:
       update_only: yes
       update_cache: yes
     when: ansible_distribution in ["CentOS","OracleLinux"]
   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

 - hosts: all
   tasks:
   - name: create simone user
     tags: always
     user:
            name: simone
            groups: root
   - name: add ssh key for simone
     tags: always
     authorized_key: 
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXA1VfGdy2cBO8By7qs1IeK2GhSAWW0BrFVgVNwmGsd ansible"

   - name: add sudoers file for simone
     copy:
            src: sudoer_simone
            dest: /etc/sudoers.d/simone
            owner: root
            group: root
            mode: 440


   - name: install httpd package (CentOS)
     tags: apache,OracleLinux,httpd
     dnf:
       name:
         - httpd
       state: latest
     when: ansible_distribution in ["CentOS","OracleLinux"]
   - name: install apache2 package (Ubuntu)
     tags: apache,apache2,ubuntu
     apt:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: install mariadb server package (CentOS)
     tags: centos,db,mariadb
     dnf:
       name: mariadb
       state: latest
     when: ansible_distribution == "CentOS"

   - name: install mariadb server
     tags: db,mariadb,ubuntu
     apt:
       name: mariadb-server
       state: latest
     when: ansible_distribution == "Ubuntu"

   - name: install samba package
     tags: samba
     package:
       name: samba
       state: latest
   - name: copying files
     tags: apache,apache2,httpd
     copy:
             src: default_site.html
             dest: /var/www/html/index.html
             owner: root
             group: root
             mode: 0644
   - name: starting httpd for CentOS
     tags: servicestart
     service:
             name: httpd
             state: started
             enabled: yes
     when: ansible_distribution == "CentOS"
 - hosts: workstations
   tasks:
     - name: install unzip
       package:
               name: unzip
     - name: install terraform
       unarchive:
               src: https://releases.hashicorp.com/terraform/1.1.2/terraform_1.1.2_linux_amd64.zip
               dest: /usr/local/bin
               remote_src: yes
               mode: 0755
               owner: root
               group: root
            
